let faixaAtual=null, questoes=[], indice=0, selecionada=null, acertos=0, stats={};
const $=id=>document.getElementById(id);
function tela(id){document.querySelectorAll('.tela').forEach(x=>x.classList.remove('ativa'));$(id).classList.add('ativa');window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('.idade').forEach(btn=>btn.addEventListener('click',()=>iniciar(btn.dataset.faixa)));
function iniciar(faixa){faixaAtual=faixa;questoes=[...bancoPerguntas[faixa]];indice=0;selecionada=null;acertos=0;stats={};tela('teste');mostrar();}
function mostrar(){const q=questoes[indice];$('contador').textContent=`Questão ${indice+1} de ${questoes.length}`;$('progresso').style.width=`${((indice+1)/questoes.length)*100}%`;$('categoria').textContent=q[3];$('pergunta').textContent=q[0];$('alternativas').innerHTML='';selecionada=null;$('proxima').disabled=true;q[1].forEach((texto,i)=>{const b=document.createElement('button');b.className='alternativa';b.textContent=`${String.fromCharCode(65+i)}. ${texto}`;b.onclick=()=>{document.querySelectorAll('.alternativa').forEach(x=>x.classList.remove('selecionada'));b.classList.add('selecionada');selecionada=i;$('proxima').disabled=false;};$('alternativas').appendChild(b);});$('proxima').textContent=indice===questoes.length-1?'Ver resultado':'Próxima';}
$('proxima').onclick=()=>{if(selecionada===null)return;const q=questoes[indice],cat=q[3];if(!stats[cat])stats[cat]={ok:0,total:0};stats[cat].total++;if(selecionada===q[2]){acertos++;stats[cat].ok++;}indice++;if(indice<questoes.length)mostrar();else resultado();};
function resultado(){const pct=Math.round(acertos/questoes.length*100);$('percentual').textContent=`${pct}%`;$('acertos').textContent=`${acertos} de ${questoes.length} acertos`;$('mensagem').textContent=pct>=85?'Desempenho muito alto neste conjunto de questões.':pct>=70?'Bom desempenho neste conjunto de questões.':pct>=50?'Desempenho intermediário. Há espaço para melhorar em algumas categorias.':'Este conjunto apresentou um nível de dificuldade elevado para você.';const box=$('categoriasResultado');box.innerHTML='';Object.entries(stats).forEach(([cat,s])=>{const p=Math.round(s.ok/s.total*100);box.innerHTML+=`<div class="linha-cat"><span>${cat}</span><span>${p}%</span><div class="mini-barra"><div style="width:${p}%"></div></div></div>`;});tela('resultado');}
$('reiniciar').onclick=()=>tela('inicio');$('voltar').onclick=()=>{if(confirm('Deseja sair do teste? O progresso atual será perdido.'))tela('inicio');};
